# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 3 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to distribution folder
  dist: "dist"

  # These files will be copied to the distribution folder
  # and must be linked individually. (They are not compiled
  # into the main CSS and JavaScript files.)
  # Files in src/assets will be copied over automatically.
  copycss:
    # e.g.
    # - "bower_components/slick-carousel/slick/slick.css"

  copyjavascript:
     - "bower_components/jquery/dist/jquery.js"
     # - "bower_components/foundation-sites/dist/js/foundation.min.js"
     - "bower_components/what-input/dist/what-input.js"
     # - "bower_components/jquery_lazyload/jquery.lazyload.js"
  copylibs:

  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"

  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    - "bower_components/foundation-sites/js/foundation.offcanvas.js"
    - "bower_components/foundation-sites/js/foundation.sticky.js"
    - "node_modules/picturefill/dist/picturefill.min.js"
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
